language: node_js
# nodejs版本
node_js: 
    - '11'

# Travis-CI Caching
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage


# S: Build Lifecycle
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run test
  - npm run cover

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
